---
resume:
  info:
    first_name: Rick
    last_name: Mark
    email_address: rickmark@outlook.com
    location: San Francisco, CA
    telephone_number: +1 (206) 913-3215
    resume_url: https://rickmark.me
    latitude: 37.7885
    longitude: -122.3986
    website_url: www.rickmark.me
    resume_print_url: https://indd.adobe.com/view/a6f34f27-9886-4b8c-820d-ecf3ec69d8eb
    pgp_key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQENBFnpTdQBCACd+STX1gHQgnnKc9yc4wQj4MXSZwdfwWZ3gBzMU6XpbWs8uGwm
      Nk7R9Xx6sc09X8eSB2/wC3IHjHtEwjosfDx5OA98D8nSZW5CcLs9TBnTQyTTsiOa
      2sDWx1pZ5B7Cgyiwa82PGVyVwwc7bJKrJ70rySlAIJbfV1A90SPWl3YzEvLDBlIl
      bPrRlMYcR58DTZxLx34KK3qHjZ5wwkU87vcU1ZVIh2vyVlmHGC+rQsPTM/gP9LCw
      ZzoPSAfnSmmSLTwRu5GqKC6XoHi1NysIN1PJOsYpAXioeJ9XotYDWIcFFrkpx1HK
      ECVQPg5AA+RMxdjzuTQIg46UIBqDFLltS9HdABEBAAG0PFJpY2sgTWFyayAoUmlj
      ayBNYXJrIC0gUHJpbWFyeSBUb2tlbikgPHJpY2ttYXJrQG91dGxvb2suY29tPokB
      VwQTAQgAQQIbAwUJA8JnAAULCQgHAgYVCAkKCwIEFgIDAQIeAQIXgBYhBEBS8Q24
      /J0opA2YgxAajy9zL/MgBQJZ6U5eAhkBAAoJEBAajy9zL/MgRcQH/1xFPaiNITO5
      /ZezhvPatQFxwks0gaPw1+SeFV+Nz9Og5qMP7iZ/NrVXqLuLbZP8J2F/UmPIdShI
      WI17yCOQRcmDeCq7NStCAjTZAV5dyQoUFlgQCOReToBNHzmeXIuQ4K20LA9+/LsS
      6HQGA0SD5xnfDhSHqNgmio7msIK2h8Ci3VwUeXzWyVcoVsbbolnOaRFNcRSnD7SF
      /EU+xWLn2jprQ1mgUFGByFVXPbAkT6MAuR9W9xa1w+iwKCtYMbKEmaFcZFKAxGnS
      qV1KuolnUr4rXEnvjbnYZ3z3sLkMNjyIp04RceiQlskPr8S8kL1e/Ngh2fpC7XDh
      GxQbWk5ypfK5AQ0EWelN1AEIAKCD1uOOJYXrADq1eGLJUpNISLfkNxHKwmzHJBQc
      c6cVqVGbTx/pDuwlfUjiLGKRQOWScSCBvX/CMzGVBY3L1Sw3cUu2IfaF35uOec9s
      py70M43QaWndFeYXZUoTP+inHFdg+vxjQ/3vW+XJNbfgWHjOn1s44b4MR0Kd4FRU
      jonX4EkE6//O1PkSSAe3V3sEh9oLGa+OXDEFw/fQflhj9RpHB5VXISllPaeSRvtr
      T/F5g9Z2ZdvFru2PnRO+SMmSG3lllINunZowqtYSUXBfabVNakUazjVtyMOcjmqH
      zQcHWn5NKiqn7nks36ChOYbxFn1LVa99bd/A7C5FKZRYujkAEQEAAYkBPAQYAQgA
      JhYhBEBS8Q24/J0opA2YgxAajy9zL/MgBQJZ6U3UAhsgBQkDwmcAAAoJEBAajy9z
      L/MgbEAH/RYqfOOOwuLaPcxUTW6LcA4zJFY5nt/foon0zWmDFuj3ehZgGbGXTkRq
      pwqyEDgUSCXKFrcJQ+v3cmTSg1y4KmuFSd+hzoGYzhVEKwb4PjRi7yZ6iegxAxIm
      i99Bx+jMM/wQS0NrFX7sGsuQti85jIyQmRga6iZSDh40E9Oy/IpCTXX11kTTPlF2
      7iWu4ZK7mFsXpXlLySwa0NrSe9RiTrPSD4bDTf76cZUKwnIVUOdeV0/UqoAk5QfI
      RFPDphKqt5D+qT544fkHDvUUu+ylj+t/qyl4sQZFIpSqYATomPAVTJ6s/d0HWBgi
      1tkfhtfjFakU/c3kLb/5ZveBanh/FVm5AQ0EWelN1AEIAL0Kbvs2ruz9zu8M0FrR
      CnxhObla3GsH4QyT7M0abUBdvd7XMyidSiqFo2N/f/6gLD7eGsVUMfL/F7sWwClI
      2YhkqNvH5LFshpIL4Z3kX2OTqtAoVOTxR0hZ7U65mt1COoJb90cn6a+NxfrojZ9n
      TMBoX5uRoTMoGaVqFVEU8QAvboOUBdDXCSYCjmLnKFyiu9pqrrdoENVl8CUmM4Sm
      gbMUga5ncAMy268JUNHcNiclmObsTZmUkiEDmP8/+lIeMQVTSvwQzcYdUlO50pcU
      LQR7NeLRM2xS9p8a+g8fn3RSuLYucbnRRwleTl+NPNGbOiNstvTgITvo70xvKcy9
      8Q0AEQEAAYkBPAQYAQgAJhYhBEBS8Q24/J0opA2YgxAajy9zL/MgBQJZ6U3UAhsM
      BQkDwmcAAAoJEBAajy9zL/Mgch0H/2EZV6d10Cdkf+IzGiw98k3ISOvskkQ3BIv4
      +d+4ExwLgV4LWcO5HDTSFnqgLLH0fsmfVfVEfUyIY1Bvedp0xFP4yMavu9pYo5B6
      9cwIXFDiQEIbAQOig4jTkBGk3PsMeK2XYq6fJuM/XFwb5fBWaS2U1iGO80sIYwj6
      83KtiPV/hF6yrcLu8y7uTlbPmqska7Bt34riA/xJwF/K12qn1adCMawiWW005OFR
      /saOXH4+ZpvEPgUSlLzaSubQ9QUCUlNI7Zr0ekIVHtH0tQ9QNHvcq4OCScOh6IjZ
      EU/qJJME5EyKWYDWzZEMZjXtxYj+GXm7T1tpdEjEEbndMh3UlY8=
      =/zpG
      -----END PGP PUBLIC KEY BLOCK-----
    social_links:
      - name: linkedin
        display: LinkedIn
        url: https://www.linkedin.com/in/penwellr
      - name: facebook
        display: Facebook
        url: https://www.facebook.com/penwellr
      - name: twitter
        display: Twitter
        url: https://twitter.com/almightylinuxgo
      - name: key
        display: Keybase
        url: https://keybase.io/rickmark
  work_history:
    - date: 'June 2017 - Current'
      name: 'Uber Advanced Technologies Group'
      link: https://www.uber.com/info/atg/
      title: 'Senior Security Engineer'
      location: 'San Francisco, CA'
    - date: 'Jan 2017 - Current'
      name: 'Hot Mess'
      link: https://hotmess.social
      title: 'Owner'
      location: 'New York, NY'
    - date: 'Feb 2016 - Dec 2017'
      name: 'Jet.com'
      link: https://jet.com
      title: 'Senior Security Engineer III'
      location: 'Hoboken, NJ'
    - date: 'Oct 2015 - Feb 2016'
      name: 'Bloomberg LP'
      link: https://bloomberglaw.com
      title: 'Senior Web Application Engineer'
      location: 'New York, NY'
    - date: 'Oct 2010 - Apr 2015'
      name: 'Microsoft Corporation'
      link: https://azure.com
      title: 'Security Software Engineer II'
      location: 'Redmond, WA'
    - date: 'Feb 2009 - June 2010'
      name: 'Phoenix Media Communications Group'
      title: 'Senior Developer'
      location: 'Boston, MA'
    - date: 'Dec 2006 - Feb 2009'
      name: 'The NASDAQ OMX Group'
      link: https://directorsdesk.com
      title: 'Analyst IV'
      location: 'Maynard, MA'
  skills:
    - name: 'Microsoft Azure / C#'
      score: 4
    - name: 'Ruby on Rails / RSpec'
      score: 4
    - name: 'Security and Cryptography'
      score: 4
    - name: 'Objective-C / Swift / AppKit / UIKit'
      score: 3
    - name: 'HTML / CSS / JS'
      score: 3
    - name: 'Azure Table / MS-SQL / MySQL / MongoDB'
      score: 3
    - name: 'Java / Java Enterprise'
      score: 2
    - name: 'C / C++ / C++ CLI / Intel & ARM Assembly'
      score: 2
  hobbies:
    - 'Publishing Articles'
    - 'Starting Companies'
    - 'Inventing Things'
    - 'Working with GLBT youth'
    - 'Supporting ending methamphetamine addiction'
  projects: []
