# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ea3f758694c4e1e21245e5a94fccdb3c7e82f4b87897066d91ea75746840fb8c22747dc488ac717456ed8ed779f60c62b45285b6ed2ff3be4eb6dd5d749ec68

test:
  secret_key_base: 3f9df7af9ee4c3f15394e4942b21724201bbebf223b782e0d8ba8eb3d3ccd45c2a02cef3431b87ed79aae6aa61f20020b6c618203d38bec496f64c423f254183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
